[
    {
        "name":"刘远超",
        "age":29,
        "score":100,
        "sex":"男"
    },
    {
        "name":"马云",
        "age":30,
        "score":98,
        "sex":"男"
    },
    {
        "name":"马化腾",
        "age":26,
        "score":28,
        "sex":"女"
    },
    {
        "name":"李彦宏",
        "age":33,
        "score":89,
        "sex":"男"
    }
]